CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;source\repos\Utar94\Wishes\backend> ^C
PS C:\Users\franc\source\repos\Utar94\Wishes\backend> cl
CREATE TABLE "Actors" (
    "ActorId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" character varying(255) NOT NULL,
    "Type" character varying(255) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DisplayName" character varying(50) NOT NULL,
    "EmailAddress" character varying(255) NULL,
    "PictureUrl" character varying(2048) NULL,
    CONSTRAINT "PK_Actors" PRIMARY KEY ("ActorId")
);

CREATE TABLE "Wishlists" (
    "WishlistId" integer GENERATED BY DEFAULT AS IDENTITY,
    "DisplayName" character varying(50) NOT NULL,
    "PictureUrl" character varying(2048) NULL,
    "ItemCount" integer NOT NULL,
    "AggregateId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Wishlists" PRIMARY KEY ("WishlistId")
);

CREATE TABLE "Items" (
    "ItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "WishlistId" integer NOT NULL,
    "Id" character varying(32) NOT NULL,
    "DisplayName" character varying(50) NOT NULL,
    "Summary" character varying(100) NULL,
    "PictureUrl" character varying(2048) NULL,
    "Rank" smallint NOT NULL,
    "RankCategory" smallint NOT NULL,
    "AveragePrice" double precision NULL,
    "MinimumPrice" double precision NULL,
    "MaximumPrice" double precision NULL,
    "PriceCategory" smallint NULL,
    "ContentText" text NULL,
    "ContentType" character varying(13) NULL,
    "Gallery" text NULL,
    "Links" text NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("ItemId"),
    CONSTRAINT "FK_Items_Wishlists_WishlistId" FOREIGN KEY ("WishlistId") REFERENCES "Wishlists" ("WishlistId") ON DELETE CASCADE
);

CREATE INDEX "IX_Actors_DisplayName" ON "Actors" ("DisplayName");

CREATE INDEX "IX_Actors_EmailAddress" ON "Actors" ("EmailAddress");

CREATE UNIQUE INDEX "IX_Actors_Id" ON "Actors" ("Id");

CREATE INDEX "IX_Actors_IsDeleted" ON "Actors" ("IsDeleted");

CREATE INDEX "IX_Actors_Type" ON "Actors" ("Type");

CREATE INDEX "IX_Items_AveragePrice" ON "Items" ("AveragePrice");

CREATE INDEX "IX_Items_CreatedBy" ON "Items" ("CreatedBy");

CREATE INDEX "IX_Items_CreatedOn" ON "Items" ("CreatedOn");

CREATE INDEX "IX_Items_DisplayName" ON "Items" ("DisplayName");

CREATE INDEX "IX_Items_MaximumPrice" ON "Items" ("MaximumPrice");

CREATE INDEX "IX_Items_MinimumPrice" ON "Items" ("MinimumPrice");

CREATE INDEX "IX_Items_PriceCategory" ON "Items" ("PriceCategory");

CREATE INDEX "IX_Items_Rank" ON "Items" ("Rank");

CREATE INDEX "IX_Items_RankCategory" ON "Items" ("RankCategory");

CREATE INDEX "IX_Items_Summary" ON "Items" ("Summary");

CREATE INDEX "IX_Items_UpdatedBy" ON "Items" ("UpdatedBy");

CREATE INDEX "IX_Items_UpdatedOn" ON "Items" ("UpdatedOn");

CREATE INDEX "IX_Items_Version" ON "Items" ("Version");

CREATE UNIQUE INDEX "IX_Items_WishlistId_Id" ON "Items" ("WishlistId", "Id");

CREATE UNIQUE INDEX "IX_Wishlists_AggregateId" ON "Wishlists" ("AggregateId");

CREATE INDEX "IX_Wishlists_CreatedBy" ON "Wishlists" ("CreatedBy");

CREATE INDEX "IX_Wishlists_CreatedOn" ON "Wishlists" ("CreatedOn");

CREATE INDEX "IX_Wishlists_DisplayName" ON "Wishlists" ("DisplayName");

CREATE INDEX "IX_Wishlists_ItemCount" ON "Wishlists" ("ItemCount");

CREATE INDEX "IX_Wishlists_UpdatedBy" ON "Wishlists" ("UpdatedBy");

CREATE INDEX "IX_Wishlists_UpdatedOn" ON "Wishlists" ("UpdatedOn");

CREATE INDEX "IX_Wishlists_Version" ON "Wishlists" ("Version");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231018140429_InitialMigration', '7.0.12');

COMMIT;
