name: Deploy Production Frontend

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build & Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build & Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_WEBAPP_DEPLOYMENT_TOKEN_PRODUCTION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          app_build_command: "npm run build"
          output_location: "dist"
